export default [
  {
    id: '1',
    first: 'Dominador',
    last: 'Dela cruz',
    userName: 'Dominador Dela cruz',
    userImg: require('../images/alex-vinogradov-BO7kc38mkGU-unsplash.jpg'),
    messageTime: '4 mins ago',
    messageText: 'Helu gudmorneng!!!',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '2',
    first: 'Bj',
    last: 'Cablao',
    userName: 'Bj Cablao',
    userImg: require('../images/alp-duran-pVHRC3e9_XM-unsplash.jpg'),
    messageTime: '2 hours ago',
    messageText: 'Gart Gart Gart',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '3',
    first: 'Toper',
    last: 'Fantastic',
    userName: 'Toper Fantastic',
    userImg: require('../images/dave-hoefler-gqLJxCHQs5w-unsplash.jpg'),
    messageTime: '1 hours ago',
    messageText: 'More More More',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '4',
    first: 'Mimi',
    last: 'yuuh',
    userName: 'Mimi yuuh',
    userImg: require('../images/daniel-j-schwarz-REjuIrs2YaM-unsplash.jpg'),
    messageTime: '1 day ago',
    messageText: 'owwwsshhhii!!!.',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '5',
    first: 'Pablo ',
    last: 'Job',
    userName: 'Pablo  Job',
    userImg: require('../images/nicola-pavan-Q4VZGRZiPfk-unsplash.jpg'),
    messageTime: '2 days ago',
    messageText: 'On The way',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '6',
    first: 'miguel',
    last: 'lito',
    userName: 'miguel  lito',
    userImg: require('../images/alex-vinogradov-BO7kc38mkGU-unsplash.jpg'),
    messageTime: '4 mins ago',
    messageText: 'Helu gudmorneng!!!',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '7',
    first: 'mary',
    last: 'tes',
    userName: 'mary  tes',
    userImg: require('../images/alp-duran-pVHRC3e9_XM-unsplash.jpg'),
    messageTime: '2 hours ago',
    messageText: 'Gart Gart Gart',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '8',
    first: 'chooks',
    last: 'togo',
    userName: 'chooks togo',
    userImg: require('../images/dave-hoefler-gqLJxCHQs5w-unsplash.jpg'),
    messageTime: '1 hours ago',
    messageText: 'More More More',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
  {
    id: '9',
    first: 'we',
    last: 'love',
    userName: 'we love',
    userImg: require('../images/daniel-j-schwarz-REjuIrs2YaM-unsplash.jpg'),
    messageTime: '1 day ago',
    messageText: 'owwwsshhhii!!!.',
    userIcon: require('../icon/icons8-thumbs-up-30.png'),
  },
];
